const FastingPizzas = [
  {
    id: 1,
    pizza_name: "Fasting Margherita",
    owner_name: "Healthy Eats",
    owner_image: "profile5.png",
    toppings: ["Tomato Sauce", "Fresh Mozzarella", "Basil"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 100,
    image: "/Fasting Margherita.png",
  },
  {
    id: 2,
    pizza_name: "Fasting Veggie Supreme",
    owner_name: "Green Kitchen",
    owner_image: "profile4.png",
    toppings: ["Spinach", "Bell Peppers", "Mushrooms", "Olives"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 120,
    image: "/Fasting Veggie Supreme.png",
  },
  {
    id: 3,
    pizza_name: "Fasting Spinach & Feta",
    owner_name: "Mediterranean Bites",
    owner_image: "profile3.png",
    toppings: ["Spinach", "Feta Cheese", "Garlic"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 110,
    image: "/Fasting Spinach & Feta.png",
  },
  {
    id: 4,
    pizza_name: "Fasting Pesto Veggie",
    owner_name: "Healthy Cravings",
    owner_image: "profile2.png",
    toppings: ["Pesto Sauce", "Zucchini", "Cherry Tomatoes"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 140,
    image: "/Fasting Pesto Veggie.png",
  },
  {
    id: 5,
    pizza_name: "Fasting Caprese Delight",
    owner_name: "Fresh Flavors",
    owner_image: "profile1.png",
    toppings: ["Tomato Slices", "Fresh Mozzarella", "Basil Pesto"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 115,
    image: "/Fasting Caprese Delight.png",
  },
  {
    id: 6,
    pizza_name: "Fasting BBQ Veggie",
    owner_name: "Grill & Chill",
    owner_image: "profile.png",
    toppings: ["BBQ Sauce", "Corn", "Red Onion", "Bell Peppers"],
    quantity: 1,
    created_at: "2024-10-01T00:30:23.018Z",
    price: 125,
    image: "/Fasting BBQ Veggie.png",
  },
];
export default FastingPizzas;
